### ISSUE TITLE
Update Branching decisions?

### ISSUE THREAD

**Issue by remingtonc** [cisco-ie/ie-git-guide#3]
So for our branching methodology going forward, are we using a development branch for feature branches that merges into master? Or are we expecting all feature branches to be stable at pull request and go straight into master?

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/cisco-ie/ie-git-guide/3/9169c313-8674-4c13-bc69-6e4c32895204/aed66b4a-27a4-48ec-8687-8df818d8059d) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/cisco-ie/ie-git-guide/3/9169c313-8674-4c13-bc69-6e4c32895204/aed66b4a-27a4-48ec-8687-8df818d8059d) for details.

**Comment by brh55** [comment]
@remingtonc @skkumaravel 

`Sprint` + `Feature` Branch.
1. `Sprint` branch is created during start of sprint
2. `Feature` branch is created on start of sprint
`If` feature branch completes --> Merge to `Sprint`
`Else` feature branch continues to progress
3. `If` CI Passes `&&` End of sprint: `Sprint` branch merges into `Master`

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by remingtonc** [comment]
@brh55 Requesting this is specified directly in guide.

**Comment by brh55** [comment]
@remingtonc  suggestions on where it should fit?

**Comment by remingtonc** [comment]
Directly before Required Readings section. Immediately jump in with a graphic/explanation.

**Comment by brh55** [comment]
@remingtonc the readme now includes a full page scenario of a 2 sprint timeline.
